### ISSUE TITLE
NPS between 3.0 and 4.0 compilations [Question]

### ISSUE THREAD

**Issue by rwbc** [Disservin/Smallbrain#116]
Hi Max,

Just a little question for verification I did not break something for my compilations.

For my old hardware nps from start pos (go depth 17 e.g.) between 3.0 and 4.0 compilations
went down from around 1Mns to 700Kns, ofc time to depth is much better now and much less
nodes are searched. So I guess this is expected from the changes?

```
id name Smallbrain Version 3.0
...
info depth 17 seldepth 24 score cp 46 nodes 25942018 nps 1018000 time 25481 pv e2e4 e7e5 g1f3 b8c6 f1b5 a7a6 b5c6 d7c6 b1c3 f7f6 d2d4 c8g4 d4e5 d8d1 c3d1 g4f3 g2f3 f6e5
bestmove e2e4

```

```
id name Smallbrain Version 4.0
...
info depth 17 seldepth 22 score cp 49 nodes 6763612 nps 701000 time 9646 pv e2e4 c7c5 c2c3 g8f6 e4e5 f6d5 g1f3 b8c6 f1b5 a7a6 b5c6 d7c6 e1g1 g7g6 f1e1 f8g7 d2d3
bestmove e2e4

```

Incredible the further nodes reduction to current dev ;-)
```
id name Smallbrain Version 4.2dev r230

info depth 17 seldepth 22 score cp 51 nodes 1061907 nps 670000 time 1583 pv e2e4 e7e6 g1f3 d7d5 e4d5 e6d5 d2d4 g8f6 f1d3 c7c5 e1g1 b8c6 f1e1 f8e7 d4c5 e8g8 c1e3 d5d4
bestmove e2e4
```

Guenther

**Comment by Disservin** [comment]
Thanks for asking^^
I think there are multiple ways to explain this:
1. Ofc new features like a stack thats used during search.
 
2. A different search tree. Pawn move generation and King move generation are the most expensive ones. Sliders are actually cheaper. So I guess while the engine gets stronger and searches the tree differently, the number of pawn movegen calls change drastically. Maybe with a stronger engine it exchanges less pawns and thus calls pawn move generation more often than a weaker version, that simplifies down ? Thats ofc just I guess. The node reduction is actually insane, from 25million to 1 million!

3. Maybe one of my commits was actually a "huge" slowdown. I think I will go back a bit in my commit history and check the speeds. Although IIRC the `bench` nps has stayed relatively consistent 

I get `nps 988000` for my recent dev version, while I think my macbook m1 gets 3mnps (WTF!)

**Comment by Disservin** [comment]
Hi Guenther/@rwbc,

I just merged a patch that should increase the nps nicely. Also think you were getting different results because of the different time. With more pruning the engine reaches a higher depth in less time, so if you compare the speeds for certain depths the results may vary because one has been measured of a larger amount of time and is probably more precise. So I think you should get some more nps if instead you let all version search for about 30 seconds and take the last reported nps.
