### ISSUE TITLE
Undeclared Identifier

### ISSUE THREAD

**Issue by Negatil07** [Disservin/Smallbrain#117]
/data/data/com.termux/files/home/Smallbrain/jni/../src/board.cpp:448:37: fatal error: use of undeclared identifier 'DEFAULT_CHECKMASK'
    checkMask = newMask ? newMask : DEFAULT_CHECKMASK;
                                    ^
1 warning and 1 error generated.
make: *** [/data/data/com.termux/files/home/android-ndk-r24/build/core/build-binary.mk:424: /data/data/com.termux/files/home/Smallbrain/obj/local/arm64-v8a/objs/Smallbrain/__/src/board.o] Error 1

**Comment by Disservin** [comment]
Check my comment from the old issue.

**Comment by Negatil07** [comment]
I will always do the make clean before compiling but the error exist.
