### ISSUE TITLE
the code execution cannot proceed because libstdc++-6.dll was not found

### ISSUE THREAD

**Issue by TheDarkKnightRise** [Disservin/Smallbrain#275]
Hi! I downloaded Smallbrain Release from this link : https://github.com/Disservin/Smallbrain/actions/runs/3786574495 

but show error :

![image](https://user-images.githubusercontent.com/121218340/209673007-92937114-cc09-4f56-b02e-9568c75e6430.png)

**Comment by Disservin** [comment]
Hi,

this should be now fixed I think try again at <https://github.com/Disservin/Smallbrain/actions/runs/3787842759> and let me know if it works.

**Comment by TheDarkKnightRise** [comment]
I need also bmi2 version 

can i please update smallbrain release ?

https://github.com/Disservin/Smallbrain/releases/

**Comment by Disservin** [comment]
The releases have a bmi2 version?

**Comment by TheDarkKnightRise** [comment]
![image](https://user-images.githubusercontent.com/121218340/209762057-84bd104e-abd1-4b4e-8e99-5d6cb9f16fdb.png)

**Comment by Disservin** [comment]
the releases at https://github.com/Disservin/Smallbrain/releases/

**Comment by TheDarkKnightRise** [comment]
but this is **Smallbrain v6.0** ,I need **Smallbrain v6.1** with la(s)test update

https://github.com/Disservin/Smallbrain/actions/runs/3787516824

**Comment by Disservin** [comment]
https://github.com/Disservin/Smallbrain/actions/runs/3793159577

these should have bmi2 now

**Comment by TheDarkKnightRise** [comment]
Excellent , Thanks
