### ISSUE TITLE
Enable SmallBrain Discussions

### ISSUE THREAD

**Issue by TheDarkKnightRise** [Disservin/Smallbrain#282]
Hi! SmallBrain is one of the best chess engines  , Please enable Discussions page inside wiki  , Thanks

**Comment by TheDarkKnightRise** [comment]
The Discussions page is useful for **ideas**, **questions and answers**, and **general discussions**

**Comment by TheDarkKnightRise** [comment]
I have many questions & ideas on small-brain & chess-library , Can i please enable discussions page ?

**Comment by Disservin** [comment]
its enabled, but post chess-library stuff at the chess-library repo
