### ISSUE TITLE
use NNUE file

### ISSUE THREAD

**Issue by tissatussa** [Disservin/Smallbrain#319]
hi, thanks for the new v7.0 NNUE .. the compilation on Linux went well and it runs fine in CuteChess .. i copied your NNUE file into the same folder, but i'm not sure if that's needed .. the README is unclear : your binary is about 3.2 Mb in size and i guess the data of the nnue file could easily be embedded, but the UCI options show the nnue file name, as if another nnue can also be used ? And if the value is left empty, will it play without NNUE ?

```
$ ./smallbrain_v7.0_compiled_HP 
uci
id name Smallbrain dev-20230129-f1192fb
id author Disservin

option name Hash type spin default 16 min 1 max 57344
option name EvalFile type string default nn-dfb6dafd17fab88-380.nnue
option name Threads type spin default 1 min 1 max 256
option name SyzygyPath type string default <empty>
option name UCI_Chess960 type check default false
uciok
```

**Comment by Disservin** [comment]
At compilation the nn is included in the produced binary during that compilation it needs to be present in the directory. After compilation you can copy the executable anywhere you like and it will have the neural net included and use that. The UCI option to choose a different binary is mainly to use older nets if one wants to (given they are trained for the same net architecture).

**Comment by tissatussa** [comment]
@Disservin that's clear .. you could include this info in the README ? thanks
