### ISSUE TITLE
NN for the "4 Knights Position" ?

### ISSUE THREAD

**Issue by tissatussa** [Disservin/Smallbrain#320]
Some time ago i stumbled upon this position :

`8/p5pp/1pk5/5p2/P1nn4/2NN3P/5PPK/8 w - - 0 1`

![4-knights-pos-white-move](https://user-images.githubusercontent.com/1109281/215358236-3d58edca-4d35-489b-a585-ec2ebcd278d7.png)

White to move

Black is a pawn ahead and he can try to win ..
White must not try to win the game and he can make a draw in many ways .. Black should keep 1 pawn alive and try to promote it, without a pawn Black cannot win, even with 2 knights .. i know not many engines seem to know this fact about the game of chess, but Smallbrain (v7.0 NNUE) does.

it's really a magical position .. many times i let engines play from this position to see how they act - for that i use longer time controls about 10m .. zugzwang often occurs, threats to promote, sacrifices of a knight for two pawns, and more "mechanisms".

you may test this position, and train an NN for it ?
one that always draws with White and can always win with Black ..!?!
it's still unclear to me .. as a chessplayer myself i'm fascinated.

here's a game with `Fortuna`, an obscure engine i once found, it has no version number - is it a Fruit clone ? See https://github.com/visanalexandru/Fortuna .. i guess its ELO is about 2600, it's not CCRL listed.

```
[Event "engine vs engine"]
[Site "Holland @ https://lichess.org/Y5PBmTSA "]
[Date "2023.01.29"]
[Round "?"]
[White "Smallbrain v7.0 NNUE"]
[Black "Fortuna"]
[Result "1/2-1/2"]
[FEN "8/p5pp/1pk5/5p2/P1nn4/2NN3P/5PPK/8 w - - 0 1"]
[GameDuration "00:15:14"]
[PlyCount "39"]
[SetUp "1"]
[TimeControl "600+10"]

1. g4 {-3.30/32 37s} Nd6 {+1.19/13 40s} 2. gxf5 {-3.39/33 22s} N6xf5 {+1.23/13 38s} 3. Kg2 {-3.45/32 40s} h5 {+1.32/13 37s} 4. Kg1 {-2.90/29 22s} g5 {+1.36/12 36s} 5. f4 {-2.36/31 25s} gxf4 {+1.37/13 34s} 6. Nxf4 {-2.05/30 8.5s} h4 {+1.41/13 33s} 7. Ne4 {-1.75/29 17s} b5 {+1.84/13 32s} 8. axb5+ {-1.65/27 11s} Kxb5 {+1.85/15 31s} 9. Kf2 {-1.58/27 21s} a5 {+1.90/14 30s} 10. Ke1 {-1.51/26 17s} a4 {+2.19/13 29s} 11. Nc3+ {-0.24/28 12s} Kb4 {+3.24/14 28s} 12. Nxa4 {-0.24/34 9.5s} Kxa4 {+3.67/14 27s} 13. Kd2 {-0.24/37 8.6s} Kb4 {+3.67/14 26s} 14. Kd3 {-0.24/38 13s} Kc5 {+3.62/16 25s} 15. Ng6 {-0.24/39 15s} Ne6 {+3.68/16 25s} 16. Ke4 {-0.24/42 8.4s} Nfd4 {+3.66/15 24s} 17. Ke5 {0.00/32 8.8s} Ng5 {+3.68/15 23s} 18. Nxh4 {0.00/39 41s} Nxh3 {+3.75/15 23s} 19. Nf5 {0.00/35 15s} Nxf5 {+4.05/15 22s} 20. Kxf5 {0.00/119 0.86s, Draw by insufficient mating material} 1/2-1/2
```

![smallbrain-vs-fortuna](https://user-images.githubusercontent.com/1109281/215358275-fc02f788-c1dd-4f62-a64b-9dde3b9f3d6f.png)

**Comment by Disservin** [comment]
This makes little sense there’s no way to train a net on a single position and the statement:

Always draw with white and always win with black is contradicting.
This makes no sense

**Comment by tissatussa** [comment]
> Always draw with white and always win with black is contradicting.
> This makes no sense

sure, i was meant to trigger a reaction and study the position .. i found out the Black position can always be won, even against very strong White engines, but it's not easy, many engines fail, therefor i tend to consider this position as a special test case for the strength of an engine.

i see you closed this Issue - that's OK with me. It's a pitty it didn't give you a new direction though.

**Comment by Disservin** [comment]
Well while it may be an interesting position a neural net can’t be trained on one standalone position
