### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by SzotsGabor** [Disservin/Smallbrain#321]
Hi Max,

The engine displays Smallbrain dev-20230129-f1192fb as its version, that might cause confusion. Version 6.0 had 6.0 in its name, maybe you could do that with version 7.0 as well?

Gabor Szots
CCRL testing group

**Comment by Disservin** [comment]
Hi, the supplied binaries should have 7 in their name. Only if you compile yourself it doesn’t have this.

**Comment by SzotsGabor** [comment]
OK, I thought I had gone mad. Now it displays 7 indeed.
