### ISSUE TITLE
Cannot Solved Puzzle

### ISSUE THREAD

**Issue by Negatil07** [Disservin/Smallbrain#51]
#Puzzle 1
8/1N6/3B4/8/8/1K2k3/8/8 w - - 0 1

#Puzzle 2
8/8/8/1B6/6p1/8/4KPpp/3N2kr w - - 0 1

#Puzzle 3
8/3P3k/n2K3p/2p3n1/1b4N1/2p1p1P1/8/3B4 w - - 0 1

**Comment by Disservin** [comment]
Thanks for reporting that, but unfortunately puzzle solving is not the main focus of Smallbrain's development. 
However, I might try some changes to solve these positions but only if they gain elo.
Closing this issue.

**Comment by Negatil07** [comment]
> Thanks for reporting that, but unfortunately puzzle solving is not the main focus of Smallbrain's development. However, I might try some changes to solve these positions but only if they gain elo. Closing this issue.
