### ISSUE TITLE
Full name

### ISSUE THREAD

**Issue by SzotsGabor** [Disservin/Smallbrain#53]
Hello Max,

Can we know your full name to include in our database?

Gabor Szots, CCRL testing group

**Comment by Disservin** [comment]
Hi Gabor,
my name is Max Allendorf

**Comment by SzotsGabor** [comment]
Thank you Max. Next update will include the first blitz results of Smallbrain.

**Comment by Disservin** [comment]
Nice! I’m looking forward to that ;)

**Comment by rwbc** [comment]
Thanks for the real name, I could add Smallbrain to the XB/UCI chronology yesterday!
Also compiling it for my old hardware (no popcnt, sse4.1) worked w/o problems.
https://rwbc-chess.de/

Guenther (RWBC)
