### ISSUE TITLE
unreal perft  speed

### ISSUE THREAD

**Issue by movepicker** [Disservin/Smallbrain#55]
hi @Disservin  

unfortunately the authors of stockfish block me & I could not to continue my idea

The maximum perft speed at single core is about 20 million NPS 

But in now stockfish version you see 99 million NPS  , do is 99 million speed  real ? 

We know does not exist 99 million perft speed  !!! 

**Unreal Peft Speed**
```
Perft 6 leaf nodes: 119060324

===========================
Total time (ms) : 1192
Nodes searched  : 119060324
Nodes/second    : 99882822
```

**Real Peft Speed**
```
Perft 6 leaf nodes: 119060324

===========================
Total time (ms) : 6670
Nodes searched  : 119060324
Nodes/second    : 17850123
```

**Comment by Disservin** [comment]
Im sorry at this point you are just trolling. I told you to go on discord if you have questions since you clearly read the chats.
Now you are opening an issue in my repo that has nothing to do with my engine. 
You are blocked from here now as well.
