### ISSUE TITLE
Loosing on time for TC 60/0:15

### ISSUE THREAD

**Issue by Joachim26** [Disservin/Smallbrain#75]
Hi, nice new engine, congrats! 
Thus I forked it and compiled it on Android for Android (with GCC on Termux). Works fine, however one issue I have found: 
When playing with Droidfish an engine game SmallBrain  (all versions)  VS itself at TC 60/0:15 the game _always_ ends with losing on time of one instance which continues to calculate ♾️. For other TCs I didn't find any problems. No idea if the issue also exists on other OS. If only on Android, just forget it.

**Comment by Disservin** [comment]
Do you mean with `60/0:15` 60 moves with 15 seconds increment ? Without a start time ?

**Comment by Joachim26** [comment]
Sorry, I'm not familiar with common TC descriptions. So I copied just Droidfish:  60/0:15 means 60 moves in 15 seconds, no increment, but after 60 moves +15 s and so on.

**Comment by Disservin** [comment]
Hi! I just tested this and for 60/15+0 (15 seconds for 60 moves) I didnt have a single time loss. However for 15 seconds for the entire game I was getting about ~10% time forfeits. I might try and improve this, but 15 seconds for the entire game isnt really a realistic TC IMO.

**Comment by Joachim26** [comment]
Thanks for testing! I assumed that it is probably mainly due to Droidfish. I often use these two fastest TCs on Droidfish for human play with engines to weaken them. And for SF for example, these short TCs are no problem.
But if I really like a specific engine, then I tweak it's source a bit ;-)
This issue isn't thus a real problem for me, so only try to fix it if you think it's worth for you.
BTW: If you have an Android device you could try my releases in my fork. For self compiling you need Termux with my Makefile.
