### ISSUE TITLE
Makefile Problem

### ISSUE THREAD

**Issue by Negatil07** [Disservin/Smallbrain#91]
Your "Makefile" for NATIVE  the engine crashing after stop analysis.

..this Makefile is working

> _THIS     := $(realpath $(dir $(abspath $(lastword $(MAKEFILE_LIST)))))

> _ROOT     := $(_THIS)

> _VALFILE   = $(_ROOT)/default.net

> CC := g++

> TARGET := smallbrain

> uname_S := $(shell uname -s)

> NATIVE = -march=native

> SRCS := $(wildcard *.cpp)

> OBJS := $(patsubst %.cpp,%.o,$(SRCS))

> all: $(TARGET)

> $(TARGET): $(OBJS)

> 	$(CC) -o $@ $^

> %.o:` %.cpp

> 	$(CC) -c $(NATIVE) -DEVALFILE=\"$(EVALFILE)\" -DNDEBUG -flto -O3 -std=c++20 -Wall $<

> clean:

> 	rm -rf $(TARGET)

> .PHONY: all clean

**Comment by Negatil07** [comment]
I dont know why this will happened. I used your Makefile but the engine start to analyze and if I stop analysis the engine make terminated.

I will used above post (Makefile) the engine got no problem.

**Comment by SzotsGabor** [comment]
The only problem I have with the makefile is that its end product is an exe which says that its version is 3.1.  So maybe the source files have not been updated.

**Comment by Disservin** [comment]
> The only problem I have with the makefile is that its end product is an exe which says that its version is 3.1. So maybe the source files have not been updated.

I updated the makefile after the initial release.. that was my bad,

**Comment by SzotsGabor** [comment]
> > The only problem I have with the makefile is that its end product is an exe which says that its version is 3.1. So maybe the source files have not been updated.
> 
> I updated the makefile after the initial release.. that was my bad. EDIT: I've "rereleased" 4.0, the makefile now produces the correct name correctly.

The exe name is 4.0 now but the id it displays after the uci command is still 3.1.

**Comment by SzotsGabor** [comment]
Well, I don't know what happened, I downloaded it several times and it said 3.1. Then I deleted everything and downloaded the source again and now it's OK. Probably something was not overwritten previously.

**Comment by Disservin** [comment]
> I think your Makefile written ( NATIVE = -mcpu=apple-a14) affecting other native.

That is should only affect macOs systems... what I can imagine is that the OS you are compiling for has a different suffix, like windows has .exe and for every other os its blank

**Comment by Negatil07** [comment]
Compiled on Android Native

Analysis:
[38] 0.00 Ba4 g3 fxg3
d:38/42 16:Bd7 t:12.55 n:5663k nps:451k

**Comment by Disservin** [comment]
> Compiled on Android Native
> 
> Analysis: [38] 0.00 Ba4 g3 fxg3 d:38/42 16:Bd7 t:12.55 n:5663k nps:451k

Can you explain the problem again ? Is the engine crashing, not compiling or stuck ?

**Comment by Negatil07** [comment]
> > Compiled on Android Native
> > Analysis: [38] 0.00 Ba4 g3 fxg3 d:38/42 16:Bd7 t:12.55 n:5663k nps:451k
> 
> Can you explain the problem again ? Is the engine crashing, not compiling or stuck ? Or is it fixed now?

It is fix now.

**Comment by Negatil07** [comment]
But inside Makefile ( -mcpu=apple-a14) affected other Native architecture.
